version '3.3'
services:

  mysql-db:
    container_name: mysqldb
    image: mnlujan/mysql:latest
    volumes: 
      - ./user-data/database:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
        - "MYSQL_USER=${MYSQL_USER}"
        - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    restart: always
    network_mode: host

  asterisk:
    container_name: asterisk16-realtime
    image: mnlujan/asterisk16webrtc-realtime:latest
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - ./user-data/etc/asterisk:/etc/asterisk
      - ./user-data/var/lib/asterisk/sounds:/var/lib/asterisk/sounds
      - ./user-data/backup:/backup
      - ./user-data/etc/letsencrypt:/etc/letsencrypt
      - ./user-data/rec:/var/spool/asterisk/monitor
    depends_on:
      - certbot
      - mysql
    restart: always
    network_mode: host
    ports:
      - 5060:5060
      - 5061:5061
      - 8088:8088
      - 8089:8089
    links: 
      - mysql-db
  

  certbot:
    container_name: certbot
    image: mnlujan/certbot:latest
    restart: always
    volumes: 
      - ./user-data/etc/letsencrypt:/etc/letsencrypt
      - ./user-data/var/lib/letsencrypt:/var/lib/letsencrypt
    environment:
      - "domains=${DOMAINS}"
      - "email=${EMAIL}"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    network_mode: host

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    depends_on:
      - certbot
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - /portainer_data:/data
      - ./user-data/etc/letsencrypt:/etc/letsencrypt
      - ./user-data/var/lib/letsencrypt:/var/lib/letsencrypt
    network_mode: host
    ports:
      - 9000:9000
    command:
      --ssl
      --sslcert /etc/letsencrypt/live/certificate/fullchain.pem
      --sslkey /etc/letsencrypt/live/certificate/privkey.pem