version: '3.3'
services:
  
  web:
    container_name: web
    image: mercadomati/centrex_web
    depends_on: 
      - mysqldb
    restart: always
    network_mode: host
    tty: true
  
  mysqldb:
    container_name: mysqldb
    image: mercadomati/centrex_db
    volumes: 
      - mysql_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: host
    tty: true

  asterisk:
    container_name: asterisk16
    image: mnlujan/asterisk16-nowebrtc:dev
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - ./user-data/etc/asterisk:/etc/asterisk
      - ./user-data/var/:/var/lib/asterisk/agi-bin/
    restart: always
    network_mode: host
    depends_on: 
      - mysqldb
    privileged: true  
    
volumes: 
  mysql_data: